package in.himanshugawari.java.javaprogrammingmasterclass.equalsandhashcode;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * @author himanshu
 *
 */
public class EqualsAndHashCode {
	private static Map<String, HeavenlyBody> solarSystem = new HashMap<String, HeavenlyBody>();
	private static Set<HeavenlyBody> planets = new HashSet<HeavenlyBody>();

	public static void main(String[] args) {
		HeavenlyBody temp = new HeavenlyBody("Mercury", 88);
		solarSystem.put(temp.getName(), temp);
		planets.add(temp);

		temp = new HeavenlyBody("Venus", 225);
		solarSystem.put(temp.getName(), temp);
		planets.add(temp);

		temp = new HeavenlyBody("Earth", 365);
		solarSystem.put(temp.getName(), temp);
		planets.add(temp);

		HeavenlyBody tempMoon = new HeavenlyBody("Moon", 27);
		solarSystem.put(tempMoon.getName(), tempMoon);
		temp.addMoon(tempMoon);

		temp = new HeavenlyBody("Mars", 687);
		solarSystem.put(temp.getName(), temp);
		planets.add(temp);

		tempMoon = new HeavenlyBody("Deimos", 1.3);
		solarSystem.put(tempMoon.getName(), tempMoon);
		temp.addMoon(tempMoon); // temp is still Mars

		tempMoon = new HeavenlyBody("Phobos", 0.3);
		solarSystem.put(tempMoon.getName(), tempMoon);
		temp.addMoon(tempMoon); // temp is still Mars

		temp = new HeavenlyBody("Jupiter", 4332);
		solarSystem.put(temp.getName(), temp);
		planets.add(temp);

		tempMoon = new HeavenlyBody("Io", 1.8);
		solarSystem.put(tempMoon.getName(), tempMoon);
		temp.addMoon(tempMoon); // temp is still Jupiter

		tempMoon = new HeavenlyBody("Europa", 3.5);
		solarSystem.put(tempMoon.getName(), tempMoon);
		temp.addMoon(tempMoon); // temp is still Jupiter

		tempMoon = new HeavenlyBody("Ganymede", 7.1);
		solarSystem.put(tempMoon.getName(), tempMoon);
		temp.addMoon(tempMoon); // temp is still Jupiter

		tempMoon = new HeavenlyBody("Callisto", 16.7);
		solarSystem.put(tempMoon.getName(), tempMoon);
		temp.addMoon(tempMoon); // temp is still Jupiter

		temp = new HeavenlyBody("Saturn", 10759);
		solarSystem.put(temp.getName(), temp);
		planets.add(temp);

		temp = new HeavenlyBody("Uranus", 30660);
		solarSystem.put(temp.getName(), temp);
		planets.add(temp);

		temp = new HeavenlyBody("Neptune", 165);
		solarSystem.put(temp.getName(), temp);
		planets.add(temp);

		temp = new HeavenlyBody("Pluto", 248);
		solarSystem.put(temp.getName(), temp);
		planets.add(temp);

		System.out.println("Planets");
		for (HeavenlyBody planet : planets) {
			System.out.println("\t" + planet.getName());
		}

		HeavenlyBody body = solarSystem.get("Earth");
		System.out.println("Moons of " + body.getName());
		for (HeavenlyBody jupiterMoon : body.getSatellite()) {
			System.out.println("\t" + jupiterMoon.getName());
		}

		body = solarSystem.get("Mars");
		System.out.println("Moons of " + body.getName());
		for (HeavenlyBody jupiterMoon : body.getSatellite()) {
			System.out.println("\t" + jupiterMoon.getName());
		}

		Set<HeavenlyBody> moons = new HashSet<>();
		for (HeavenlyBody planet : planets) {
			moons.addAll(planet.getSatellite());
		}

		System.out.println("All Moons");
		for (HeavenlyBody moon : moons) {
			System.out.println("\t" + moon.getName());
		}

		HeavenlyBody pluto = new HeavenlyBody("Pluto", 842);
		planets.add(pluto);

		planets.forEach(planet -> System.out.println(planet.getName() + " : " + planet.getOrbitalPeriod()));
	}
}

final class HeavenlyBody {
	private final String name;
	private final double orbitalPeriod;
	private final Set<HeavenlyBody> satellite;

	public HeavenlyBody(String name, double orbitalPeriod) {
		super();
		this.name = name;
		this.orbitalPeriod = orbitalPeriod;
		this.satellite = new HashSet<>();
	}

	public boolean addMoon(HeavenlyBody moon) {
		return this.satellite.add(moon);
	}

	public String getName() {
		return name;
	}

	public double getOrbitalPeriod() {
		return orbitalPeriod;
	}

	public Set<HeavenlyBody> getSatellite() {
		return new HashSet<>(this.satellite);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		System.out.println("obj.getClass() is " + obj.getClass());
		System.out.println("this.getClass() is " + this.getClass());
		if (obj == null || this.getClass() != obj.getClass()) {
			return false;
		}
		String objName = ((HeavenlyBody) obj).getName();
		return this.name.equals(objName);
	}

	@Override
	public int hashCode() {
		System.out.println("hashCode() called");
		return this.name.hashCode() + 57;
	}

	// generated by eclipse
//	@Override
//	public int hashCode() {
//		System.out.println("hashCode() called");
//		final int prime = 31;
//		int result = 1;
//		result = prime * result + ((name == null) ? 0 : name.hashCode());
//		long temp;
//		temp = Double.doubleToLongBits(orbitalPeriod);
//		result = prime * result + (int) (temp ^ (temp >>> 32));
//		result = prime * result + ((satellite == null) ? 0 : satellite.hashCode());
//		return result;
//	}
//
//	@Override
//	public boolean equals(Object obj) {
//		System.out.println("obj.getClass() is " + obj.getClass());
//		System.out.println("this.getClass() is " + this.getClass());
//		if (this == obj)
//			return true;
//		if (obj == null)
//			return false;
//		if (getClass() != obj.getClass())
//			return false;
//		HeavenlyBody other = (HeavenlyBody) obj;
//		if (name == null) {
//			if (other.name != null)
//				return false;
//		} else if (!name.equals(other.name))
//			return false;
//		if (Double.doubleToLongBits(orbitalPeriod) != Double.doubleToLongBits(other.orbitalPeriod))
//			return false;
//		if (satellite == null) {
//			if (other.satellite != null)
//				return false;
//		} else if (!satellite.equals(other.satellite))
//			return false;
//		return true;
//	}

}